### ISSUE TITLE
Order structure is missing on MongoDB

### ISSUE THREAD

**Issue by VittorioMorellini** [Abdullah-moiz/nextjs-ecommerce#1]
Hi Abdoullah,
the data structure for orders is not created automatically.

Do I have to manually create the structure on MongoDB?
I can follow the mongoose structuire from the source code so create the structure on Mongo
The convention is plural names and not Capitalize the first letter, isn't it?

I can be a contributor to new feature if you like, tell me if you get pleasure to have a little contributor or to have a simple tester.
I am going to create the database by myself for order struture or do you prefer to give the structure?

Best Regards
Vittorio Morellini

**Comment by Abdullah-moiz** [comment]
Order schema is defined already, I just pushed another commit where you can track order details , Two option available 1 next to bookmark button and 1 option is available in hamburger menu . 

Application is currently under development .
