### ISSUE TITLE
Admin Issue 

### ISSUE THREAD

**Issue by Aman9641** [Abdullah-moiz/nextjs-ecommerce#6]
I have cloned your project but when I use admin login it will take a 2 sec pause to admin page and then redirect to home page and there is no product how to correct it ?

**Comment by Abdullah-moiz** [comment]
when you register a new user by default it is consider as user role 

1.  go to mongodb compass 
2.  select e-commerce collection  
3.  select User documents
4. find new registered user 
5. change role to admin
6. save the document
7. now clear login again 
8. you will be redirected to admin dashboard now you can add a new product
